---
- name: nvm dir is present
  file:
    path: '{{ home_dir }}/.nvm'
    state: directory

- name: nvm is present
  shell: wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash

